input.onButtonPressed(Button.A, function () {
    rif1()
    basic.pause(imellom)
    rif2()
    basic.pause(imellom)
    rif1()
    basic.pause(imellom)
    rif3()
})
function rif2 () {
    music.playTone(523, music.beat(BeatFraction.Quarter))
    basic.pause(imellom)
    music.playTone(523, music.beat(BeatFraction.Quarter))
    basic.pause(imellom)
    music.playTone(523, music.beat(BeatFraction.Quarter))
    basic.pause(imellom)
    music.playTone(523, music.beat(BeatFraction.Eighth))
    basic.pause(imellom)
    music.playTone(523, music.beat(BeatFraction.Quarter))
    basic.pause(imellom)
    music.playTone(494, music.beat(BeatFraction.Quarter))
    basic.pause(imellom)
    music.playTone(494, music.beat(BeatFraction.Quarter))
    basic.pause(imellom)
    music.playTone(494, music.beat(BeatFraction.Quarter))
    basic.pause(imellom)
    music.playTone(494, music.beat(BeatFraction.Quarter))
    basic.pause(imellom)
    music.playTone(440, music.beat(BeatFraction.Quarter))
    basic.pause(imellom)
    music.playTone(440, music.beat(BeatFraction.Quarter))
    basic.pause(imellom)
    music.playTone(494, music.beat(BeatFraction.Quarter))
    basic.pause(imellom)
    music.playTone(440, music.beat(BeatFraction.Half))
    basic.pause(imellom)
    music.playTone(587, music.beat(BeatFraction.Half))
}
function rif1 () {
    music.playTone(494, music.beat(BeatFraction.Quarter))
    basic.pause(imellom)
    music.playTone(494, music.beat(BeatFraction.Quarter))
    basic.pause(imellom)
    music.playTone(494, music.beat(BeatFraction.Half))
    basic.pause(imellom)
    music.playTone(494, music.beat(BeatFraction.Quarter))
    basic.pause(imellom)
    music.playTone(494, music.beat(BeatFraction.Quarter))
    basic.pause(imellom)
    music.playTone(494, music.beat(BeatFraction.Half))
    basic.pause(imellom)
    music.playTone(494, music.beat(BeatFraction.Quarter))
    basic.pause(imellom)
    music.playTone(587, music.beat(BeatFraction.Quarter))
    basic.pause(imellom)
    music.playTone(392, music.beat(BeatFraction.Quarter))
    basic.pause(imellom + 50)
    music.playTone(440, music.beat(BeatFraction.Eighth))
    basic.pause(imellom)
    music.playTone(494, music.beat(BeatFraction.Whole))
}
function rif3 () {
    music.playTone(523, music.beat(BeatFraction.Quarter))
    basic.pause(imellom)
    music.playTone(523, music.beat(BeatFraction.Quarter))
    basic.pause(imellom)
    music.playTone(523, music.beat(BeatFraction.Quarter))
    basic.pause(imellom)
    music.playTone(523, music.beat(BeatFraction.Eighth))
    basic.pause(imellom)
    music.playTone(523, music.beat(BeatFraction.Quarter))
    basic.pause(imellom)
    music.playTone(494, music.beat(BeatFraction.Quarter))
    basic.pause(imellom)
    music.playTone(494, music.beat(BeatFraction.Quarter))
    basic.pause(imellom)
    music.playTone(494, music.beat(BeatFraction.Quarter))
    basic.pause(imellom)
    music.playTone(587, music.beat(BeatFraction.Quarter))
    basic.pause(imellom)
    music.playTone(587, music.beat(BeatFraction.Quarter))
    basic.pause(imellom)
    music.playTone(523, music.beat(BeatFraction.Quarter))
    basic.pause(imellom)
    music.playTone(440, music.beat(BeatFraction.Quarter))
    basic.pause(imellom)
    music.playTone(392, music.beat(BeatFraction.Whole))
}
let imellom = 0
basic.showIcon(IconNames.Heart)
imellom = 150
basic.forever(function () {
	
})
